[RFC] [topik-change-data-and-component-routing] (Решение задания 10)
vkosinov/junior-course-boilerplate pull request #10
Opened 2020-02-16 12:51 UTC by vkosinov

2020-02-17 18:30 UTC, vislogurov requested changes

2020-02-17 18:30 UTC, vislogurov commented on src/containers/AddToCart.js
> +  const value = added ? `Убрать${long ? ' из корзины' : ''}` : `Добавить${long ? ' в корзину' : ''}`;
Нужно стараться избегать такой цепочки тернарных операторов, в большинстве случаев, когда есть соблазн подобной конструкции, скорей всего ты что то делаешь не так

2020-02-17 18:30 UTC, vislogurov commented on src/containers/SidebarCart.js
> +      {items.length !== 0 && (
Давай так: сразу после того, как деструктурировал `items` из пропсов, ты сделаешь проверку.

```
if (!item.length) {
   return null
}
```
И тогда до рендера Cart вообще не дойдёт дело.

2020-02-17 18:30 UTC, vislogurov commented on src/store/cart/actions.js
> +          dispatch(errorCart(response.message));
А чем эта ветка отличается от `.catch(error =>...`? Когда выполнится `else`, а когда `catch?`

2020-02-17 18:30 UTC, vislogurov commented on src/components/Cart/Cart.jsx
> +        {ok === 'OK' && <img className={s.ok} src="/assets/img/ok.svg" alt="ok" />}
1) Непонятно, что значит `ok`. Если это состояние, то замени на `isSuccess` или `isProceed`.
2) Зачем нужен alt (вообще, в принципе)? Какую информацию выдаст скринридер дойдя до этого аттрибута? И что из этой информации извлечёт слабовидящий человек? Иконки в 98% случаев это чисто декоративные элементы, best-practice на этот случай использовать `bacground-image`, иначе см. выше про alt и img)

2020-02-17 18:30 UTC, vislogurov commented on src/containers/AddToCart.js
> +      toggleToCart([...items.filter(item => item !== id)]);
Выше ты уже получаешь полную копию items, а тут ещё раз делаешь полную копию копии. Зачем?

2020-02-17 19:29 UTC, vkosinov commented on src/containers/AddToCart.js
> +      toggleToCart([...items.filter(item => item !== id)]);
Если речь про эту строчку 
```const added = items.find(item => item === id);```

Тут я не проверяю добавлен ли товар в корзину далее если добавлен то возвращаю массив без этого элемента, если не добавлен добавляю его в конец существующего массива

2020-02-18 06:40 UTC, vislogurov commented on src/containers/AddToCart.js
> +      toggleToCart([...items.filter(item => item !== id)]);
я про `...items`

2020-02-18 06:49 UTC, vkosinov commented on src/containers/AddToCart.js
> +      toggleToCart([...items.filter(item => item !== id)]);
Поправил

2020-02-18 18:47 UTC, vislogurov requested changes

2020-02-18 18:47 UTC, vislogurov commented on src/pages/ProductsPage/ProductsPage.jsx
> +        <div className={s.aside}>
тут явно напрашивается вместо дива `aside`

2020-02-18 18:47 UTC, vislogurov commented on src/components/Button/styles.module.css
> +  cursor: not-allowed;
лучше `pointer-events: none` тогда клик точно не пройдёт.

2020-02-18 18:47 UTC, vislogurov commented on src/components/ProductList/ProductList.jsx
> +import AddToCart from '../../containers/AddToCart';
Лучше `AddToCardContainer`, `AddToCart` выглядит, как функция добавления чего то в корзину, хотя тут целый компонент.

2020-02-19 07:00 UTC, vislogurov approved these changes

2020-02-19 16:39 UTC, merged