[RFC] [context] (решение задания 5)
vkosinov/junior-course-boilerplate pull request #5
Opened 2020-01-26 11:34 UTC by vkosinov

2020-01-27 18:00 UTC, vislogurov requested changes

2020-01-27 18:00 UTC, vislogurov commented on src/utils.js
> +export const getSelectedProduct = (items, minPrice, maxPrice, discount, category) => {
Кажется, что getSelectedProduct и getCategory делают одно и тоже. Если так, то давай сделаем из этого универсальную функцию.

2020-01-27 18:08 UTC, vkosinov commented on src/utils.js
> +export const getSelectedProduct = (items, minPrice, maxPrice, discount, category) => {
`getSelectedProduct` - возвращает список продуктов в зависимости от выбранных фильтров

`getCategory` - возвращается список не повторяющихся категорий которые в сайт баре потом появляются 

 Может переименовать как то ,  что бы было более очевидно ?

2020-01-28 07:12 UTC, vislogurov approved these changes

2020-01-28 07:16 UTC, merged