[WIP] [routing]  (Решение задания 8)
vkosinov/junior-course-boilerplate pull request #8
Opened 2020-02-06 13:31 UTC by vkosinov

2020-02-07 15:50 UTC, CSSSR-School requested changes
Помимо замечаний по коду, заметил не совсем корректное поведение при установленных фильтрах и переходах по страницам. В этом случае фильтры сбрасываются, хотя не должны. 

Видео воспроизведения: http://s.csssr.ru/U04LFCTTB/2020-02-07-1847-iq4nm94agu.mp4

2020-02-07 15:50 UTC, CSSSR-School commented on src/components/App/App.jsx
> +          <Provider store={store}>
А зачем ты кладешь сюда еще один Provider, если он уже определен выше?

2020-02-07 15:50 UTC, CSSSR-School commented on src/components/pages/ProductPage/ProductPage.jsx
> +              <div className={s.rating}>☆ ☆ ☆ ★ ★</div>
А почему бы нам тут не переиспользовать ранее созданный компонент `ratingComponent`? Рейтинг же должен совпадать с тем, что выводится на странице списка товаров, а сейчас получается он статичный

2020-02-07 15:50 UTC, CSSSR-School commented on src/containers/List.js
> +      activeCategory: router.location.query.category,
В прошлый раз пропустили( Так использовать селекторы нельзя. В селектор должно попадать все состояние твоего приложения. А уже внутри, на основе всего состояния, вычисляется структура, которая тебе необходима на выходе селектора.

Селектор всегда работает со всем состоянием приложения. Если у тебя в каком-то месте состояния изменится какое-то поле (кто-то решил переименовать его), то в текущем варианте тебе придется бегать по компонентам и искать где нужно внести правки, а компоненты не должны ничего знать о структуре твоего redux-хранилища. Они просто должны вызывать доступные им селекторы.

Компонент как бы говорит "Мне пофиг, что у тебя там внутри, вот я знаю такой селектор и у меня есть ссылка на состояние хранилища. Дай мне данных".

Вот изучи такой доклад одного из наших сотрудников. В нем показаны лучшие практики использования библиотеки `reselect`: https://www.youtube.com/watch?v=tg3CRiAMz-s

Внеси правки во всех частях приложения, где допущены такие ошибки

2020-02-07 15:50 UTC, CSSSR-School commented on src/store/filter/selectors.js
> +const itemsPerPage = 2;
Думаю что можно оставить `6` и просто увеличить кол-во продуктов в JSON файлике. Но это просто совет, править не обязательно

2020-02-07 16:03 UTC, vkosinov commented on src/components/pages/ProductPage/ProductPage.jsx
> +              <div className={s.rating}>☆ ☆ ☆ ★ ★</div>
Хорошо что это прояснилось) Про него не где не сказано поэтому его роль у меня выполняет функция из примера 

```
const ratingComponent = ({ isFilled }) => {
  return <div className={isFilled ? 'starFill' : ''} />;
};
```

Приведу к подобающему виду, тоже смутило и было под вопросом для уточнения ) Спасибо!

2020-02-07 16:07 UTC, vkosinov commented on src/components/pages/ProductPage/ProductPage.jsx
> +              <div className={s.rating}>☆ ☆ ☆ ★ ★</div>
Заменил на 

```
const ratingComponent = ({ isFilled }) => {
  return isFilled ? '★' : '☆';
};
```

вынес отдельно, реиспользовал

2020-02-10 15:28 UTC, CSSSR-School requested changes
Еще есть моменты, которые необходимо исправить

2020-02-10 15:28 UTC, CSSSR-School commented on src/containers/List.js
>        products,
Так тоже не очень верно делать. В селектор первым аргументом должно попадать состояние твоего приложения. А уже последующими можно передавать дополнительные данные. Одной из фишек `createSelector` является мемоизация. Которая срабатывает если ссылка на входящее состояние не меняется. А у тебя тут всегда новый объект в селектор попадает.

Но в целом, ты же может весь список продуктов также положить в твое хранилище. И внутри селектора забирать из нужного места список продуктов.

2020-02-10 15:28 UTC, CSSSR-School commented on src/containers/List.js
> +    activePage: state.router.location.query.page,
Хорошо бы конечно и на это написать селекторы, чтобы логика получения этих данных хранилась в одном месте (на будущее)

2020-02-10 15:28 UTC, CSSSR-School commented on src/store/filter/selectors.js
> +  ({ router }) => router.location.query.category,
Вот например тут ты дублируешь логику получения категории. Уже напрашивается вынос этого в отдельный селектор

2020-02-11 14:35 UTC, CSSSR-School commented
@vkosinov теперь все ок. Можешь вливать в `master` и двигаться дальше

2020-02-11 14:36 UTC, merged